spring:
  application:
    name: StudentPlacement
  datasource:
    url: jdbc:postgresql://localhost:5432/Student-Placement
    username: postgres
    password: shivparvati

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "cVrp.1.,&fF.?}j&$yo;9^AB1fMuFK<H#:<qB&DrC@T"
  expiration: 86400000
