spring:
  application:
    name: StudentPlacement
  datasource:
    url: jdbc:postgresql://localhost:5432/Student-Placement
    username: postgres
    password: shivparvati

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: lakshay
      password: lakshay
